[package]
name = "tauri-bindgen-cli"
authors = ["Jonas Kruckenberg <iterpre@protonmail.com>"]
version.workspace = true
edition.workspace = true

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
wit-parser = { git = 'https://github.com/bytecodealliance/wasm-tools' }
wit-component = { git = 'https://github.com/bytecodealliance/wasm-tools' }
bindgen-core = { path = "crates/bindgen-core"}
gen-rust = { path = "crates/gen-rust"}
gen-host = { path = "crates/gen-host"}
gen-guest-rust = { path = "crates/gen-guest-rust"}
gen-guest-ts = { path = "crates/gen-guest-ts"}
gen-guest-js = { path = "crates/gen-guest-js"}
gen-markdown = { path = "crates/gen-markdown"}
heck =  { version = "0.4", features = ["unicode"] }
anyhow = "1.0.65"
clap = { version = "4.0.9", features = ["derive"] }
async-trait = "0.1.58"
pulldown-cmark = { version = "0.8", default-features = false }
bitflags = "1.3.2"
tauri = "1.2.0"

[dependencies]
anyhow.workspace = true
clap.workspace = true
bindgen-core.workspace = true
gen-host = { workspace = true, features = ['clap'] }
gen-markdown = { workspace = true, features = ['clap'] }
gen-guest-rust = { workspace = true, features = ['clap'] }
gen-guest-ts = { workspace = true, features = ['clap'] }
gen-guest-js = { workspace = true, features = ['clap'] }
wit-parser.workspace = true
wit-component.workspace = true
