[package]
name = "tauri-bindgen-cli"
authors = ["Jonas Kruckenberg <iterpre@protonmail.com>"]
version.workspace = true
edition.workspace = true

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
wit-parser = { git = 'https://github.com/bytecodealliance/wasm-tools' }
tauri-bindgen-core = { path = "crates/bindgen-core"}
tauri-bindgen-gen-rust = { path = "crates/gen-rust"}
tauri-bindgen-gen-host = { path = "crates/gen-host"}
tauri-bindgen-gen-guest-rust = { path = "crates/gen-guest-rust"}
tauri-bindgen-gen-guest-ts = { path = "crates/gen-guest-ts"}
tauri-bindgen-gen-guest-js = { path = "crates/gen-guest-js"}
tauri-bindgen-gen-guest-rescript = { path = "crates/gen-guest-rescript"}
tauri-bindgen-gen-markdown = { path = "crates/gen-markdown"}
heck =  { version = "0.4", features = ["unicode"] }
anyhow = "1.0.65"
clap = { version = "4.0.9", features = ["derive"] }
async-trait = "0.1.58"
pulldown-cmark = { version = "0.8", default-features = false }
bitflags = "1.3.2"
tauri = "1.2.0"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tauri-bindgen-core.workspace = true
tauri-bindgen-gen-host = { workspace = true, features = ['clap'] }
tauri-bindgen-gen-markdown = { workspace = true, features = ['clap'] }
tauri-bindgen-gen-guest-rust = { workspace = true, features = ['clap'] }
tauri-bindgen-gen-guest-ts = { workspace = true, features = ['clap'] }
tauri-bindgen-gen-guest-js = { workspace = true, features = ['clap'] }
tauri-bindgen-gen-guest-rescript = { workspace = true, features = ['clap'] }
wit-parser.workspace = true
