[package]
name = "tauri-bindgen-cli"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Jonas Kruckenberg <iterpre@protonmail.com>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.64"

[workspace.dependencies]
thiserror = "1.0.38"
bitflags = "1.3.2"
heck =  { version = "0.4", features = ["unicode"] }
clap = { version = "3.2.23", features = ["derive"] }
tauri-bindgen-core = { path = "crates/bindgen-core" }
tauri-bindgen-gen-host = { path = "crates/gen-host", features = ['cli'] }
tauri-bindgen-gen-markdown = { path = "crates/gen-markdown", features = ['cli'] }
tauri-bindgen-gen-guest-rust = { path = "crates/gen-guest-rust", features = ['cli'] }
tauri-bindgen-gen-guest-ts = { path = "crates/gen-guest-ts", features = ['cli'] }
tauri-bindgen-gen-guest-js = { path = "crates/gen-guest-js", features = ['cli'] }
wit-parser = { path = "crates/wit-parser" }
miette = { version = "5.5.0", features = ["fancy"] }
log = { version = "0.4.17", features = [ "kv_unstable", "kv_unstable_std" ] }

[dependencies]
clap.workspace = true
tauri-bindgen-core.workspace = true
tauri-bindgen-gen-host.workspace = true
tauri-bindgen-gen-markdown.workspace = true
tauri-bindgen-gen-guest-rust.workspace = true
tauri-bindgen-gen-guest-ts.workspace = true
tauri-bindgen-gen-guest-js.workspace = true
wit-parser.workspace = true
miette.workspace = true
env_logger = "0.10.0"
log.workspace = true