[package]
name = "rust-macro-shared"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
tauri-bindgen-core = { path = "../bindgen-core" }
wit-parser = { path = "../wit-parser" }
