[package]
name = "rust-macro-shared"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false
test = false

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
wit-parser.workspace = true
