[package]
name = "ipc-router-wip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
tauri-bindgen-abi = { path = "../abi" }
log.workspace = true