[package]
name = "tauri-bindgen-gen-js"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri-bindgen-core.workspace = true
wit-parser.workspace = true
heck.workspace = true
log.workspace = true
bitflags.workspace = true
