[package]
name = "tauri-bindgen-gen-rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tauri-bindgen-core = { path = "../bindgen-core" }
wit-parser = { path = "../wit-parser" }
heck =  { version = "0.4", features = ["unicode"] }