[package]
name = "gen-guest-rust"
version.workspace = true
edition.workspace = true

[dependencies]
gen-rust.workspace = true
bindgen-core.workspace = true
wit-parser.workspace = true
heck.workspace = true
clap = { workspace = true, optional = true }

[dev-dependencies]
wit-component.workspace = true
anyhow.workspace = true
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.32"
js-sys = "0.3.59" 
guest-rust = { path = "../guest-rust" }
serde = { version = "1.0.140", features = ["derive"] }

[features]
clap = ["dep:clap"]