[package]
name = "tauri-bindgen-gen-guest-rust"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tauri-bindgen-core.workspace = true
tauri-bindgen-gen-rust = { path = "../gen-rust" }
wit-parser.workspace = true
heck.workspace = true
clap = { workspace = true, optional = true }
quote = "1.0.23"
proc-macro2 = "1.0.52"
syn = "1.0.109"
prettyplease = "0.1.24"
log.workspace = true

[dev-dependencies]
wasm-bindgen = { version = "0.2.84", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.34"
serde-wasm-bindgen = "0.5.0"
js-sys = "0.3.61" 
tauri-bindgen-guest-rust = { path = "../guest-rust" }
serde = { version = "1.0.155", features = ["derive"] }
pretty_assertions = "1.3.0"

[features]
cli = ["clap"]
