[package]
name = "tauri-bindgen-gen-guest-rust"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tauri-bindgen-gen-rust = { path = "../gen-rust" }
tauri-bindgen-core.workspace = true
wit-parser.workspace = true
heck.workspace = true
clap = { workspace = true, optional = true }

[dev-dependencies]
wasm-bindgen = { version = "0.2.84", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.34"
serde-wasm-bindgen = "0.5.0"
js-sys = "0.3.61" 
tauri-bindgen-guest-rust = { path = "../guest-rust" }
serde = { version = "1.0.152", features = ["derive"] }
# tauri-bindgen-abi = { path = "../abi" }

[target."cfg(miri)".dev-dependencies]
tauri-bindgen-core = { workspace = true, features = ["miri_test"] }

[features]
cli = ["clap"]