[package]
name = "tauri-bindgen-gen-guest-rust"
version.workspace = true
edition.workspace = true

[dependencies]
tauri-bindgen-gen-rust.workspace = true
tauri-bindgen-core.workspace = true
wit-parser.workspace = true
heck.workspace = true
clap = { workspace = true, optional = true }

[dev-dependencies]
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.33"
serde-wasm-bindgen = "0.4.5"
js-sys = "0.3.60" 
tauri-bindgen-guest-rust = { path = "../guest-rust" }
serde = { version = "1.0.152", features = ["derive"] }

[features]
clap = ["dep:clap"]