[package]
name = "tauri-bindgen-guest-rust-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
tauri-bindgen-gen-guest-rust = { path = "../gen-guest-rust" }
rust-macro-shared = { path = "../rust-macro-shared" }