[package]
name = "tauri-bindgen-guest-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
tauri-bindgen-guest-rust-macro = { path = "../guest-rust-macro" }
serde-wasm-bindgen = "0.4.5"
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60" 
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }
serde = { version = "1.0.152", features = ["derive"] }
