[package]
name = "tauri-bindgen-guest-rust"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags.workspace = true
tauri-bindgen-guest-rust-macro = { path = "../guest-rust-macro" }
serde-wasm-bindgen = "0.4.5"
wasm-bindgen-futures = "0.4.32"
js-sys = "0.3.59" 
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
serde = { version = "1.0.140", features = ["derive"] }