[package]
name = "tauri-bindgen-host"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
tauri-bindgen-host-macro = { path = "../host-macro" }
async-trait = "0.1.57"
tauri.workspace = true
serde = { version = "1.0.140", features = ["derive"] }
tracing = { version = "0.1.26", features = ["log", "log-always"] }