[package]
name = "tauri-bindgen-host"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags.workspace = true
tauri-bindgen-host-macro = { path = "../host-macro" }
async-trait = "0.1.59"
tauri.workspace = true
serde = { version = "1.0.151", features = ["derive"] }
tracing = { version = "0.1.37", features = ["log", "log-always"] }