[package]
name = "host-macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
gen-host.workspace = true
rust-macro-shared = { path = "../rust-macro-shared" }