[package]
name = "tauri-bindgen-gen-host"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

[dependencies]
tauri-bindgen-gen-rust = { path = "../gen-rust" }
tauri-bindgen-core = { path = "../bindgen-core" }
wit-parser = { path = "../wit-parser" }
heck =  { version = "0.4", features = ["unicode"] }
clap = { version = "3.2.23", features = ["derive"], optional = true }

[dev-dependencies]
tauri-bindgen-host = { path = "../host" }
serde = { version = "1.0.152", features = ["derive"] }

[target."cfg(miri)".dev-dependencies]
tauri-bindgen-core = { path = "../bindgen-core", features = ["miri_test"] }

[features]
cli = ["clap"]