[package]
name = "tauri-bindgen-gen-host"
version.workspace = true
edition.workspace = true

[dependencies]
tauri-bindgen-gen-rust.workspace = true
tauri-bindgen-core.workspace = true
wit-parser.workspace = true
heck.workspace = true
clap = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
tauri-bindgen-host = { path = "../host" }
serde = { version = "1.0.149", features = ["derive"] }

[features]
clap = ["dep:clap"]