[build.environment]
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = 'playground/dist'
  command = """
    wget -qO- https://github.com/thedodd/trunk/releases/download/${VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
    npx pnpm install --store=node_modules/.pnpm-store
    cd playground/editor
    pnpx tsup --target esnext --platform browser --format esm --minify index.ts
    cd ../..
    trunk build --release
  """