[build.environment]
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = 'dist'
  command = """
    cd editor
    npx pnpm install --store=node_modules/.pnpm-store
    pnpm tsup index.ts --target esnext --platform browser --format esm --minify
    cd ..
    wget -qO- https://github.com/thedodd/trunk/releases/download/${VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
    trunk build --release
  """