[package]
name = "tauri-bindgen-core"
version.workspace = true
edition.workspace = true

[dependencies]
wit-parser.workspace = true
blake3 = { version = "1.3.3", features = ["rayon"] }
memmap2 = "0.5.8"
rayon = "1.6.1"
hex = "0.4.3"
thiserror.workspace = true
miette.workspace = true
bitflags.workspace = true
