[package]
name = "tauri-bindgen-core"
version.workspace = true
edition.workspace = true

[dependencies]
wit-parser.workspace = true
blake3 = { version = "1.3.2", features = ["rayon"] }
memmap2 = "0.5.3"
rayon = "1.6.0"
hex = "0.4.3"
anyhow.workspace = true